spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taobao?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8900
#  ssl:
#    key-store: classpath:inymtern.xyz.jks
#    key-store-password: inymtern